package:
  name: packlab
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../
  git_url: https://github.com/MartinPdeS/PackLab.git

build:
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  number: 0

channels:
  - conda-forge
  - martinpdes

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python {{ PY_VER }}*
    - scikit-build-core ~=0.3.*
    - pybind11 ~=2.13.*
    - python-build ~=1.2.*
    - setuptools_scm[toml] ~=8.0.*
    - numpy ==2.2.*
  run:
    - pandas ==2.3.*
    - martinpdes::mpsplots
    - matplotlib ==3.8.*
    - numpy ==2.2.*
    - pydantic ==2.9.*

about:
  home: https://github.com/MartinPdeS/PackLab
  license: MIT
  summary: "A package for particle packing simulation."
  description: "PackLab"
  dev_url: https://github.com/MartinPdeS/PackLab
  doc_url: https://martinpdes.github.io/PackLab/
  license_file: LICENSE
  keywords:
    - packing
    - particle
    - simulation

files:
  include:
    - "PackLab/binary/*.so"

test:
  imports:
    - PackLab
  requires:
    - python {{ PY_VER }}*
    - pytest >=0.6.*
    - pytest-cov >=2.0.*
    - pytest-json-report ==1.5.*
    - coverage ==7.6.*
  commands:
    - python -m pytest
  source_files:
    - tests

extra:
  recipe-maintainers:
    - MartinPdeS
