from typing import Any

class PercusYevickDomain:
    def __init__(self, size: Any, radii: Any, volume_fraction: float, number_fractions: Any, rounding_mode: Any = ...) -> None: ...
    size: Any
    radii: Any
    volume_fraction: float
    number_fractions: Any
    particle_densities_per_radius: Any
    def sample_radii(self, number_of_samples: int, seed: int | None = None) -> Any: ...
    def print_bins(self, precision: int = 6) -> None: ...
    def bins_table(self, precision: int = 6) -> str: ...
