from typing import Any

class PackingDomain:
    def __init__(self, length_x: Any, length_y: Any, length_z: Any, use_periodic_boundaries: bool) -> None: ...
    @property
    def length_x(self) -> Any: ...
    @property
    def length_y(self) -> Any: ...
    @property
    def length_z(self) -> Any: ...
    volume: float
    use_periodic_boundaries: bool
    def scale(self, scale_factor: float) -> None: ...
