from typing import Any

class RadiusSampler:
    @property
    def number_of_bins(self) -> int: ...
    def set_number_of_bins(self, bins: int) -> None: ...
    def to_bins(self) -> tuple[Any, Any]: ...
    def plot_histogram(self, ax: Any = ..., unit: Any = ..., **kwargs: Any) -> Any: ...

class ConstantRadiusSampler(RadiusSampler):
    def __init__(self, radius: Any, bins: int = 0) -> None: ...

class UniformRadiusSampler(RadiusSampler):
    def __init__(self, minimum_radius: Any, maximum_radius: Any, bins: int = 0) -> None: ...

class NormalRadiusSampler(RadiusSampler):
    def __init__(self, mean: Any, standard_deviation: Any, maximum_clip: Any | None = None, bins: int = 0) -> None: ...

class LogNormalRadiusSampler(RadiusSampler):
    def __init__(self, median_radius: Any, geometric_standard_deviation: float, maximum_radius_clip: Any, bins: int = 0) -> None: ...

class DiscreteRadiusSampler(RadiusSampler):
    def __init__(self, radii: Any, weights: Any) -> None: ...
